# This workflow uploads the latest wheel of hydra-core & ray-launcher to S3 bucket.

name: Update website

on:
   push:
    branches:
      - action

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and publish
      env:
        GITHUB_TOKEN: ${{ secrets.DOC_GITHUB_TOKEN }}
      run: |
        pwd
        echo $DOC_GITHUB_TOKEN
        git status
        yarn
